import chalk from 'chalk';
import ora from 'ora';
import inquirer from 'inquirer';
import * as fs from 'fs';
import * as path from 'path';
import { theme } from '../utils/theme';
import { getConfig } from '../utils/config';
import { listEmailAccounts } from '../utils/directadmin';
import { getCreds, pickDomain } from '../utils/shared';

function shellEscape(s: string): string {
  return "'" + s.replace(/'/g, "'\\''") + "'";
}

export async function backupCommand(domain?: string): Promise<void> {
  const creds = getCreds();
  const config = getConfig();
  const targetDomain = await pickDomain(creds, domain);

  console.log(theme.heading(`Mailbox Backup: ${targetDomain}`));

  const spinner = ora({ text: 'Fetching accounts...', spinner: 'dots12', color: 'cyan' }).start();

  try {
    const accounts = await listEmailAccounts(creds, targetDomain);
    spinner.stop();

    if (accounts.length === 0) {
      console.log(theme.muted('  No email accounts found.\n'));
      return;
    }

    const { selectedAccounts } = await inquirer.prompt([
      {
        type: 'checkbox',
        name: 'selectedAccounts',
        message: 'Select accounts to back up:',
        choices: [
          { name: 'All accounts', value: '__ALL__' },
          ...accounts.map((a) => ({ name: `${a}@${targetDomain}`, value: a })),
        ],
      },
    ]);

    let accountsToBackup: string[] = selectedAccounts;
    if (selectedAccounts.includes('__ALL__')) {
      accountsToBackup = accounts;
    }

    if (accountsToBackup.length === 0) {
      console.log(theme.muted('\n  No accounts selected.\n'));
      return;
    }

    const { outputDir } = await inquirer.prompt([
      {
        type: 'input',
        name: 'outputDir',
        message: theme.secondary('Backup directory:'),
        default: `./mxroute-backup-${targetDomain}-${new Date().toISOString().split('T')[0]}`,
      },
    ]);

    const server = config.server ? `${config.server}.mxrouting.net` : 'YOUR_SERVER.mxrouting.net';

    console.log(theme.heading('Backup Commands'));
    console.log(theme.muted('  The following imapsync commands will back up your mailboxes.'));
    console.log(theme.muted('  Install imapsync: https://imapsync.lamiral.info/\n'));

    const commands: string[] = [];

    for (const account of accountsToBackup) {
      const email = `${account}@${targetDomain}`;
      const backupPath = path.join(outputDir, account);

      const cmd = [
        'imapsync',
        `--host1 "${server}"`,
        '--ssl1',
        `--user1 "${email}"`,
        '--password1 "YOUR_PASSWORD"',
        `--host2 "${path.resolve(backupPath)}"`,
        '--localfolders',
        '--addheader',
      ].join(' \\\n    ');

      commands.push(cmd);

      console.log(`  ${theme.statusIcon('info')} ${theme.bold(email)}`);
      console.log(theme.muted(`  ${cmd}\n`));
    }

    // Generate shell script
    const { generateScript } = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'generateScript',
        message: 'Generate a backup shell script?',
        default: true,
      },
    ]);

    if (generateScript) {
      const scriptPath = `backup-${targetDomain}.sh`;
      const scriptContent = [
        '#!/bin/bash',
        `# MXroute mailbox backup script for ${shellEscape(targetDomain)}`,
        `# Generated by mxroute-cli on ${new Date().toISOString()}`,
        '',
        '# IMPORTANT: Replace YOUR_PASSWORD with actual passwords',
        `# Server: ${server}`,
        '',
        'set -e',
        '',
        `mkdir -p ${shellEscape(outputDir)}`,
        '',
        ...accountsToBackup.map((account) => {
          const email = `${account}@${targetDomain}`;
          const backupPath = path.join(outputDir, account);
          return [
            `echo ${shellEscape(`Backing up ${email}...`)}`,
            `mkdir -p ${shellEscape(backupPath)}`,
            `imapsync \\`,
            `  --host1 ${shellEscape(server)} \\`,
            `  --ssl1 \\`,
            `  --user1 ${shellEscape(email)} \\`,
            `  --password1 'YOUR_PASSWORD' \\`,
            `  --host2 ${shellEscape(path.resolve(backupPath))} \\`,
            `  --localfolders \\`,
            `  --addheader`,
            '',
          ].join('\n');
        }),
        `echo ${shellEscape(`Backup complete! Files saved to ${outputDir}`)}`,
        '',
      ].join('\n');

      fs.writeFileSync(scriptPath, scriptContent, { mode: 0o700 });
      console.log(theme.success(`\n  ${theme.statusIcon('pass')} Script saved: ${scriptPath}`));
      console.log(theme.warning(`  ${theme.statusIcon('warn')} Edit the script to add passwords before running.`));
    }

    console.log('');
    console.log(theme.muted('  Alternative: Use mbsync (isstretchync) or offlineimap for periodic backups.'));
    console.log(theme.muted(`  IMAP server: ${server} | Port: 993 (SSL)\n`));
  } catch (err: any) {
    spinner.fail(chalk.red('Failed to prepare backup'));
    console.log(theme.error(`  ${err.message}\n`));
  }
}
